ARG LOGSEQ_TAG

FROM ghcr.io/pengx17/logseq-base:${LOGSEQ_TAG} as logseq

FROM mcr.microsoft.com/playwright:focal

WORKDIR /home/logseq

COPY --from=logseq /home/logseq/public/ ./public
COPY --from=logseq /home/logseq/node_modules ./node_modules
COPY publish.mjs ./

CMD ["-p", "graph/", "-o", "graph/www", "-t", "true", "--theme", "light"]
ENTRYPOINT ["xvfb-run", "node", "publish.mjs"]